- appveyor.yml
- nuspecs/Hangfire.Core.nuspec
- nuspecs/Hangfire.SqlServer.MSMQ.nuspec
- nuspecs/Hangfire.SqlServer.RabbitMQ.nuspec
- nuspecs/Hangfire.SqlServer.nuspec
- nuspecs/Hangfire.nuspec
- src/Hangfire.Core/States/StateMachine.cs
- src/SharedAssemblyInfo.cs
- tests/Hangfire.Core.Tests/States/StateMachineFacts.cs
This is a correcting release. Fixed a bug related to MSMQ or RabbitMQ extensions, when enqueued job is not being processed and "stucked" in the *Enqueued* state indefinitely until we retry it manually.
* **Fixed** – Enqueued job is not being processed with MSMQ or RabbitMQ (#294).
> 1.3.3 Release

- src/Hangfire.SqlServer/SqlServerMonitoringApi.cs
Hi,
`GetTimelineStats` and `GetHourlyTimelineStats` job counts may be assigned to the wrong dates. The problem is that in the last loop where the result is generated the matching of the value of `valuesMap[valuesMap.Keys.ElementAt(i)]` and the date `dates[i]` are not correct.
for (var i = 0; i < dates.Count; i++)
{
var value = valuesMap[valuesMap.Keys.ElementAt(i)]; // valuesMap.Keys may be unsorted if keys were missing and added via valuesMap.Add(key, 0);
result.Add(dates[i], value); // dates are sorted
}
I also refactored some duplicated code into a separate function.
> Fix GetTimelineStats / GetHourlyTimelineStats incorrect order

- README.md
The twitter link `[Twitter](https://twitter.com/hangfire_net) |` was dead. Removed that from the README.md
> Update twitter link

- src/SharedAssemblyInfo.cs
Having the AssemblyFileVersion attribute defined causes the product version and file version in the dll properties to follow it. Removing it makes those properties follow the assembly version. This was causing issues within a MSI my project uses, since the MSI thinks the version is always 1.0.0.0 and skips deploying the new dll.
> Making Product Version and File Version on the dll match the Assembly Version

- src/Hangfire.SqlServer.RabbitMq/RabbitMqConnectionConfiguration.cs
- src/Hangfire.SqlServer.RabbitMq/RabbitMqSqlServerStorageExtensions.cs
- tests/Hangfire.SqlServer.RabbitMq.Tests/RabbitMqConnectionConfigurationFacts.cs
This change allows a URI to be used for the RabbitMQConnectionConfiguration. Using an AMQP URI is less verbose than having to specify each configuration property. This is backwards compatible, if no URI is specified then the default properties are expected to be set.
* Updated to point to HangFire Dev branch
> Allow a URI to be used for RabbitMQConnectionConfiguration

- README.md
- src/Hangfire.SqlServer/ExpirationManager.cs
> Remove the `with tablock` hint from the expiration cleanup

- src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
When rendering the Job Details page:
TimeSpan parameters are now rendered as TimeSpan.Parse("12:13:14")
rather than FromJson("\"12:13:14\"")
DateTime parameters are now rendered as
DateTime.Parse("2012-11-10T00:00:00.0000000") rather than
Deserialize("2012-11-10T00:00:00.0000000")
Please see issue #353 (ArgumentRenderer - Support for TimeSpan and DateTime)
> Arguments Renderer now supports TimeSpan and DateTime

- src/Hangfire.SqlServer.RabbitMq/Hangfire.SqlServer.RabbitMq.csproj
- src/Hangfire.SqlServer.RabbitMq/RabbitMqFetchedJob.cs
- src/Hangfire.SqlServer.RabbitMq/packages.config
- tests/Hangfire.SqlServer.RabbitMq.Tests/Hangfire.SqlServer.RabbitMq.Tests.csproj
- tests/Hangfire.SqlServer.RabbitMq.Tests/packages.config
In RabbitMQ.Client v3.4.0 there was introduced some namespace changes making it incompatible with current code.
Simply updated package dependencies and code for it.
> Fixed incompatibility issue with RabbitMQ.Client >=v3.4.0

- src/Hangfire.Core/Dashboard/JobHistoryRenderer.cs
Fixes #367. Added some extra validation. If Latency is bigger then TimeSpan.MaxValue.TotalMilliseconds set Latency to TimeSpan.MaxValue.TotalMilliseconds. Otherwise there will be the next overflow exception
> Fix `OverflowException` in `SucceededRenderer`

- src/Hangfire.Core/Storage/InvocationData.cs
- tests/Hangfire.Core.Tests/Common/JobHelperFacts.cs
I am serializing message DTOs into my hangfire jobs, and needed to specify `TypeNameHandling = TypeNameHandling.All` on the JsonSerializerSettings. Unfortunately this breaks the Job serialization as it attempts to serialize the unevaluated linq select statement for the method parameter array:
```
Hangfire.Common.JobLoadException : Could not load the job. See inner exception for the details.
---- Newtonsoft.Json.JsonSerializationException : Type specified in JSON 'System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.Reflection.ParameterInfo, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Type, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Core, Version=4.0.0.0, Culture=neutral, …
```
> Job serialization fix when using TypeNameHandling.All

- src/Hangfire.Core/Hangfire.Core.csproj
Added Server/BackgroundProcessContextExtensions.cs to Hangfire.Core project file.
Corrects an issue created by this commit, preventing the dev branch from building:
https://github.com/HangfireIO/Hangfire/commit/ac05704e3c0dc3d3659f2c53661f52257f467370
> Added Server/BackgroundProcessContextExtensions.cs to Hangfire.Core project

- src/Hangfire.Core/Hangfire.Core.csproj
Corrected an issue created in "Update Bootstrap to 3.3.5" (1c7784d) where the "glyphicons-halflings-regular.woff2" resource was not being embedded into Hangfire.Core.
See issue #414.
> [414] Corrected an issue created in "Update Bootstrap to 3.3.5" (1c7784d)

- src/Hangfire.Core/App_Packages/StackTraceFormatter/StackTraceFormatter.cs
- src/Hangfire.Core/App_Packages/StackTraceParser/StackTraceParser.cs
- src/Hangfire.Core/Dashboard/HtmlHelper.cs
- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.Core/MoreLinq/MoreEnumerable.Pairwise.cs
- src/Hangfire.Core/packages.config
Instead of including stack trace highlighting code from ELMAH, use the more up-to-date and stand-alone version via the StackTraceFormatter package. Addresses issue #418 and also makes sync'ing easier going forward.
> Use StackTraceFormatter for marking-up stack traces

- src/Hangfire.Core/Dashboard/HtmlHelper.cs
The typo had no impact so far as `st-params` was not styled in [`hangfire.css`](https://github.com/HangfireIO/Hangfire/blob/dev/src/Hangfire.Core/Dashboard/Content/css/hangfire.css#L186).
> Stack trace parameters CSS class typo

- src/Hangfire.SqlServer/SqlServerDistributedLock.cs
Resolved an issue where the timeout for the Stored Procedure sp_getapplock could be longer than the default timeout on the Command object. This could result in the command timing out, not the SP call, and so an unexpected exception being thrown. 
The command object now has its timeout set to be 1 second longer than the SP timeout.
> Disable concurrent execution command timeout

- src/Hangfire.SqlServer/SqlServerDistributedLock.cs
- tests/Hangfire.SqlServer.Tests/SqlServerDistributedLockFacts.cs
Previously the check was made for only `value > Int32.Max` but then 1 was added later. Now checking to see if `value >= Int32.Max`. 
Test also added for this.
> SqlServerDistributedLockTimeout - logical error in value check

- src/Hangfire.SqlServer/Constants.cs
- src/Hangfire.SqlServer/CountersAggregator.cs
- src/Hangfire.SqlServer/DefaultInstall.sql
- src/Hangfire.SqlServer/DefaultInstall.tt
- src/Hangfire.SqlServer/ExpirationManager.cs
- src/Hangfire.SqlServer/Hangfire.SqlServer.csproj
- src/Hangfire.SqlServer/SqlServerConnection.cs
- src/Hangfire.SqlServer/SqlServerJobQueue.cs
- src/Hangfire.SqlServer/SqlServerJobQueueMonitoringApi.cs
- src/Hangfire.SqlServer/SqlServerMonitoringApi.cs
- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
- src/Hangfire.SqlServer/SqlServerStorage.cs
- src/Hangfire.SqlServer/SqlServerStorageOptions.cs
- src/Hangfire.SqlServer/SqlServerWriteOnlyTransaction.cs
I came across issue https://github.com/HangfireIO/Hangfire/issues/432 and didn't see any pull request.
I would like to have multiple BackgroundJobServer's with different code bases running on the same database. Using different schemas for each code base seems like a reasonable approach to achieve this. Are there any objections to including this pull request?
I have tokenized the master install script and created a T4 template to generate the default one ([Hangfire].) that was included in the Nuget package.
> Add the ability to specify the schema for SqlServerStorage.

- src/Hangfire.Core/Dashboard/EmbeddedResourceDispatcher.cs
'Stream.CopyTo' introduced in .NET 4.5
> Simplify writing of embedded resource to response body.

- src/Hangfire.Core/States/BackgroundJobStateChanger.cs
Simple solution to break infinite loop and resolve #467.
This infinite loop happens when CancellationToken.None is used in one of the constructor overloads of 'StateChangeContext' class. 
Also maybe it is better to return null in 'GetJobData' method immediately after first try without any retries.
> Prevent infinite loops when trying to change state of a job that doesn't exist

- content/readme.txt
The link for "Configuring Dashboard authorization" when to a nonexistent page.
> Fixed documentation link

- nuspecs/Hangfire.SqlServer.MSMQ.nuspec
`Hangfire.SqlServer.Msmq.nuspec` file points to `Hangfire.SqlServer` 1.2.2 dependency instead of a current one.
> Fix Hangfire.SqlServer dependency version in MSMQ nuspec

- src/Hangfire.Core/Common/TypeExtensions.cs
- tests/Hangfire.Core.Tests/Common/TypeExtensionsFacts.cs
- tests/Hangfire.Core.Tests/Hangfire.Core.Tests.csproj
Current version of ToGenericTypeString method doesn't support nested classes. 
This is my fix for it. Commit also contains some tests to prove its correctness.
> Fix for ToGenericTypeString method to support nested classes

- src/Hangfire.Core/App_Packages/StackTraceParser/StackTraceParser.cs
- src/Hangfire.Core/packages.config
The StackTraceParser had a critical flaw that caused the server to hang when specific error messages were returned (https://github.com/atifaziz/StackTraceParser/issues/4). This just replaces the parser with the updated version to avoid such problems.
> Updating StackTraceParser to prevent critical flaw

- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.Core/JobActivator.cs
- src/Hangfire.Core/JobActivatorContext.cs
- src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs
- tests/Hangfire.Core.Tests/Server/CoreBackgroundJobPerformerFacts.cs
This allows to inject specific services in IoC containers based on background job metadata.
> Add context for JobActivator.BeginScope

- src/Hangfire.Core/Common/Job.cs
- src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs
- tests/Hangfire.Core.Tests/Common/JobFacts.cs
- tests/Hangfire.Core.Tests/Server/CoreBackgroundJobPerformerFacts.cs
Fixes #150
I also added a test that confirms that a method can accept a standard .NET `CancellationToken` and addressed two of the items mentioned on the previous PR (disallowing `async void` methods and unwrapping `AggregateException`s when possible.)
> Add support for async Task methods

- src/Hangfire.SqlServer/SqlServerFetchedJob.cs
It looks like the `transaction` argument is missing from the `Execute` call in the `KeepAliveQuery` method.
> Add missing transaction to KeepAliveQuery.

- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
- src/Hangfire.Core/Dashboard/Content/resx/Strings.Designer.cs
- src/Hangfire.Core/Dashboard/Content/resx/Strings.es.resx
- src/Hangfire.Core/Dashboard/Content/resx/Strings.resx
- src/Hangfire.Core/Dashboard/DashboardMetric.cs
- src/Hangfire.Core/Dashboard/DashboardMetrics.cs
- src/Hangfire.Core/Dashboard/Pages/HomePage.cshtml
- src/Hangfire.Core/Dashboard/Pages/HomePage.generated.cs
- src/Hangfire.Core/Dashboard/Pages/_BlockMetric.cshtml
- src/Hangfire.Core/Dashboard/Pages/_BlockMetric.generated.cs
- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.SqlServer/SqlServerStorage.cs
Adding Spanish :es: translation for Hangfire. Any correction for the strings translated will be great.
After translating I saw that all the Metrics titles always showed in english. It was because they were static, so the title was always on the default culture before setting any other culture. 
I modified them to use a TitleResourceKey and load the title from resources when asked.
> Add spanish language for the Dashboard

- src/Hangfire.SqlServer/DefaultInstall.sql
- src/Hangfire.SqlServer/Install.sql
Currently running schema 3, and the alter statements for [Hangfire].[Server].[Id] in the schema 4 => 5 transition table fail because of a the clustered index that is referencing the [Id].
This is solved by dropping the constraint, doing the alter, and adding the constraint back. 
Surprisingly enough I could not replay this with a default run of the (Default)Install.sql script. I can only replicate this with a copy of our production database. Manually recreating the table (drop + create to from SSMS) did not recreate this issue either.
> Drop constraints on Server.Id prior to altering it to avoid conflicts

- src/Hangfire.Core/Cron.cs
When scheduling Cron Jobs using the Interval functions in the Cron class it seems to just schedule the job for a minute + the interval time. Due to this the schedule job seems to execute just every minute e.g. If we call the HourInterval with 12 it would show up on the dashboard as 1minute, 12hours and it would just execute every minute.
> Fix Cron.cs for recurring jobs using intervals

- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
Fixed UI command behaviour across all pages, such that buttons can only be pressed once per command. This removes side effects such as being able to trigger the same job multiple times on the recurring jobs page. #611
> Fixed UI command behaviour

- nuspecs/Hangfire.Core.nuspec
- psake-project.ps1
Despite of the fact that internationalization support was already added to Hangfire 1.6, resource files weren't copied to their corresponding NuGet packages, leading localizations to a non-working state.
> Add l10n resource files to NuGet packages

- src/Hangfire.Core/Common/TypeExtensions.cs
- tests/Hangfire.Core.Tests/Common/TypeExtensionsFacts.cs
Fixed a bug related to the method `GetNonOpenMatchingMethod` returns incorrect method from existing overloaded methods. So if you have two methods:
```csharp
void Method(object arg) { }
void Method(SomeClass arg) {}
```
And you try enqueue job:
```csharp
var someObject = new SomeClass();
BackgroundJob.Enqueue(() => Method(someObject);
```
You expect invocation of `void Method(SomeClass arg)` method but Hangfire invokes `void Method(object arg)`.
> Fix bug related to incorrect choosing overloading method

- .travis.yml
- appveyor.yml
Configure AppVeyor and Travis CI build notifications. Notifications will be sent to Slack if build status is failure or build status is changed
> Configure AppVeyor and Travis CI build notifications

- src/Hangfire.SqlServer/SqlServerDistributedLock.cs
- tests/Hangfire.SqlServer.Tests/SqlServerDistributedLockFacts.cs
Throw argument exception when timeout milliseconds exceeds int.max. Prevents issue with sp_getapplock's @LockTimeout param.
> Fixes #657

- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.Core/Hangfire.Core.project.json
- src/Hangfire.Core/packages.config
Update CronExpressionDescriptor to 1.21.0. It fixes problem related to incorrecting tooltip of cron expression on Dashboard.
Fixes #727
> Update CronExpressionDescriptor to 1.21.0

- src/Hangfire.Core/Storage/InvocationData.cs
- tests/Hangfire.Core.Tests/Storage/InvocationDataFacts.cs
JSON exception during argument deserialization may cause `ReferenceConverter` to be used to perform the deserialization (type converters are here due to backwards compatibility). Since it couldn't properly handle serialized things, it will return null instead of re-throwing an exception, resulting in hidden error.
> Rethrow JSON exception instead of returning a null value for argument

- Hangfire.sln.DotSettings
- src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.generated.cs
If there is problem with parsing of job cron expression Recurrig Jobs page will still be displayed. 
This PR fixes #692
> Fixes occasional crashes of Recurring Jobs page

- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
In the ongoing project I was integrating Hangfire dashboard into the existing UI using simple iframe approach. To auto-size the iframe I used custom resizing handler and noticed that Hangfire throws a lot of exceptions.
1. Execute MvcSample and navigate to /hangfire URL (Chrome, Firefox, IE - all are affected).
2. Open browser's developer console.
3. Resize the window.
4. Move mouse over graphs on the dashboard.
5. Each mouse movement event will throw "Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null(…)".
6. The same exception will be also thrown periodically, event without mouse moving.
In the window.onresize handler (hangfire.js:221) existing graphs placeholders are emptied and new graphs created. During the creation phase, Rickshaw.Graph.HoverDetail adds …
> Window resize cause errors and uncontrolled growth of event and poll listeners

- src/Hangfire.Core/BackgroundJobServerOptions.cs
- src/Hangfire.Core/Obsolete/ServerWatchdogOptions.cs
- src/Hangfire.Core/Server/ServerWatchdog.cs
- tests/Hangfire.Core.Tests/Hangfire.Core.Tests.csproj
- tests/Hangfire.Core.Tests/Obsolete/ServerWatchdogOptionsFacts.cs
- tests/Hangfire.Core.Tests/Server/BackgroundJobServerOptionsFacts.cs
Validate BackgroundJobServerOptions properties:
* if ServerTimeout is non-negative and less than or equal to 24 hours. If it's not ArgumentOutOfRangeException will be thrown.
* if HeartbeatInterval  is non-negative and less than or equal to 24 hours. If it's not ArgumentOutOfRangeException will be thrown.
* if ServerCheckInterval is non-negative less than or equal to 24 hours. If it's not ArgumentOutOfRangeException will be thrown.
* if SchedulePollingInterval is less than or equal to Int32.MaxValue milliseconds and non-negative or infinite. If it's not ArgumentOutOfRangeException will be thrown.
* if ServerCheckInterva is less than or equal to Int32.MaxValue milliseconds and non-negative or infinite. If it's not ArgumentOutOfRangeException will be thrown.
Fixes #518
> Validate BackgroundJobServerOptions properties

- src/Hangfire.Core/Common/TypeExtensions.cs
- tests/Hangfire.Core.Tests/Common/TypeExtensionsFacts.cs
Add support for array of generic types like `T[]` or `Tuple<T,T>[]` as parameter type.
Related issue:  #408 
You can enqueue method with generic array parameters:
```csharp
public void Foo<T>(T[] argArray) ;
...
string[] aArray = ...;
BackgroundJob.Enqueue(() => Foo(aArray);
```
Also you can enqueue a method which has more complicated parameter type:
```csharp
public void Foo<T>(Tuple<T,int>[] argArray) ;
...
Tuple<string,int>[] aArray = ...;
BackgroundJob.Enqueue(() => Foo(aArray);
```
> Add support an array of generic type as parameter type

- src/Hangfire.Core/Storage/RecurringJobDto.cs
- src/Hangfire.Core/Storage/StorageConnectionExtensions.cs
useful for:
```
using (var connection = JobStorage.Current.GetConnection())
{
var recurrings = StorageConnectionExtensions.GetRecurringJobs(connection);
foreach (RecurringJobDto recurring in recurrings)
{
if(recurring.Queue == "APPNAME")
{
if (recurring.Id != "ID_IN_APP_DATABASE_USING_ORM")
{
RecurringJob.RemoveIfExists(recurring.Id);
}
}
}
}
```
> Make Queue name accessible from RecurringJobDto

- src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
Fixes error 500 in the dashboard when rendering an array of reference types where an element could be null.
#734
> Fixes error 500 in the dashboard

- src/Hangfire.Core/Dashboard/Content/resx/Strings.resx
Typo - "Nexts jobs" should be "Next jobs"
> Typo - "Nexts jobs" should be "Next jobs"

- src/Hangfire.Core/Dashboard/Pages/ScheduledJobsPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/ScheduledJobsPage.generated.cs
Use for Scheduled column title localized value from Strings.resx instead of string 'ScheduledJobsPage_Table_Scheduled'.
> Fix Scheduled column title

- src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml
The RecurringJobsPage only displayed 9 instead of 10 items.
> Fix number of displayed Records in RecurringJobsPage

- src/Hangfire.AspNetCore/AspNetCore/AspNetCoreJobActivatorScope.cs
Use ActivatorUtilities.GetServiceOrCreateInstance instead of ServiceProvider.GetRequiredService, this allows creating instances of notification handlers without requiring them to be registered in DoI. Otherwise GetRequiredService would throw an error if a service isn't registered. This allow the handler to be created and still apply constructor injection to the handler.
> AspNetCoreJobActivatorScope Resolve using ActivatorUtilities.GetServiceOrCreateInstance

- src/Hangfire.Core/AutomaticRetryAttribute.cs
This change will allow to add elect state filters that are able intercept the `FailedState` transition before the `AutomaticRetryAttribute` filter. For example, to set custom notifications about retries, provide custom automatic retry logic, etc. Currently this isn't possible without clearing the global filters, because `AutomaticRetryAttribute` has the lowest possible order.
> Change `AutomaticRetryAttribute` filter Order to 20

- src/Hangfire.Core/QueueAttribute.cs
It's better to make it run as an apply state filter, but this is a breaking change. This filter always should be called last, especially if previous filters are suspected in changing candidate state to the enqueued one, to not to ignore the queue setting. 
This behavior leads to bug, when continuation is created when antecedent job is already finished, and our continuation is enqueued to the `default` queue, regardless of the specified one. Steps to reproduce:
```csharp
[Queue("critical")]
public static void MyJob() {}
var antecedent = BackgroundJob.Enqueue(() => MyJob()); // critical queue
Thread.Sleep(60000); // Waiting for antecedent job to be succeeded
BackgroundJob.ContinueWith(antecedent, () => MyJob()); // default queue, wrong
```
If continuation is created before antecedent …
> Change order of the QueueAttribute state filter

- src/Hangfire.Core/AutomaticRetryAttribute.cs
- tests/Hangfire.Core.Tests/RetryAttributeFacts.cs
This PR adds ability to specify custom delays for retries via `AutomaticRetryAttribute`. 
**Specify custom delays by an integer array**. 
You can set a delay for a job:
```csharp
// All delays are the same and equal 10 seconds.
[AutomaticRetry(DelaysInSeconds = new [] { 10 })]
public void SomeJob() { ... }
// First delay is 1 second, second delay is 5 seconds, other delays are 10 seconds.
[AutomaticRetry(DelaysInSeconds = new [] { 1, 5, 10 })]
public void SomeJob() { ... }
```
Also it's possible set a delay for all jobs:
```csharp
GlobalJobFilters.Filters.Add(new AutomaticRetryAttribute { DelaysInSeconds = new { 1,5,100 }});
```
**Specify custom delay by a function.**
If you want to use complex algorithm to define a delay by a attempt you should set …
> Support custom delays for automatic retries

- src/Hangfire.Core/RecurringJobManager.cs
- src/Hangfire.Core/Server/RecurringJobScheduler.cs
- src/Hangfire.Core/States/AwaitingState.cs
- src/Hangfire.Core/States/EnqueuedState.cs
- src/Hangfire.Core/States/FailedState.cs
- src/Hangfire.Core/States/ProcessingState.cs
- src/Hangfire.Core/States/ScheduledState.cs
- src/Hangfire.Core/States/SucceededState.cs
- src/Hangfire.Core/Storage/InvocationData.cs
- src/Hangfire.Core/Storage/StorageConnectionExtensions.cs
- src/Hangfire.SqlServer/SqlServerConnection.cs
- src/Hangfire.SqlServer/SqlServerMonitoringApi.cs
- tests/Hangfire.Core.Tests/Storage/InvocationDataFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerConnectionFacts.cs
This PR fixes #816.
Serialization is cumbersome in some places. I propose the following changes:
- Do not save redundant assembly's information: Version, Culture, PublicKeyToken;
- Do not save assembly names for system types: "mscorlib" for .NET Full Framework and "System.Private.Core" for .NET Core
- Serialize InvocationData as properties array instead of json object;
**Example:**
Consider the following code
```
BackgroundJob.Enque(() => Console.WriteLine("Hello!"));
```
Current serialization of InvocationData looks like this:
```
"{\"Type\":\"System.Console, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\",\"Method\":\"WriteLine\",\"ParameterTypes\":\"[\\\"System.String, mscorlib, Version=4.0.0.0, Culture=neutral, …
```
> Reduce serialization size

- src/Hangfire.Core/JobActivator.cs
- src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs
Provides the JobActivator BeginScope with the full Performcontext.
Examples and motivation can be found here: https://github.com/HangfireIO/Hangfire/issues/828
This change is fully backward compatible with previous versions
> Fixing #828

- nuspecs/Hangfire.Core.nuspec
The .nuspec file for Hangfire.Core is currently pointing to version 5.0.0 of Newtonsoft.Json, which does not exist. The correct version is 5.0.1.
This causes these kinds of issues:
Closes #947, closes #973
> Fix nuspec pointing to version of Newtonsoft.Json that does not exist

- src/Hangfire.Core/Dashboard/HtmlHelper.cs
- src/Hangfire.Core/Dashboard/IDashboardJobNameProvider.cs
- src/Hangfire.Core/Dashboard/RazorPage.cs
- src/Hangfire.Core/DashboardOptions.cs
- src/Hangfire.Core/Hangfire.Core.NetStandard.csproj
- src/Hangfire.Core/Hangfire.Core.csproj
Because of shortcomings of `DisplayNameAttribute` (or lack thereof on .NET Core), I'd like to propose another approach to job naming: `IDashboardJobNameProvider`.
Like `IDashboardAuthorizationFilter`s, name provider is configured in `DashboardOptions` during startup, and implements a single method taking current `DashboardContext` (so you have access to Owin environment or .NET Core's `HttpContext`) and the `Job` of interest. 
Here's an example of what it looks like:
``` c#
public class SampleJobNameProvider : IDashboardJobNameProvider
{
public string GetName([NotNull] DashboardContext context, [NotNull] Job job)
{
// You may implement different approaches for job naming, be it an attribute ...
string jobName = job.Method.GetCustomAttribute<DisplayNameAttribute>()?.DisplayName;
if …
```
> Add entry point for custom job naming strategies

- src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs
- tests/Hangfire.Core.Tests/Common/JobFacts.cs
- tests/Hangfire.Core.Tests/Hangfire.Core.Tests.project.json
- tests/Hangfire.Core.Tests/Server/CoreBackgroundJobPerformerFacts.cs
C# 7 adds support for [generalized async return types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#generalized-async-return-types), i.e. async method may not only return `Task` subclass but also an arbitrary object with `GetAwaiter()` method, e.g. `ValueTask<T>`.
> Support async jobs returning ValueTask<T>

- src/Hangfire.Core/App_Packages/LibLog.1.4/LibLog.cs
follow up PR for fix for log4net for dotnet standard #1096
GetLogger(string name) no longer exists in log4net dotnet core. Use GetLogger(Assembly assembly, string name) as fallback
fixes #1095
> change log4net method

- src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardContext.cs
- src/Hangfire.AspNetCore/HangfireApplicationBuilderExtensions.cs
- src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs
- src/Hangfire.Core/BackgroundJobServer.cs
- src/Hangfire.Core/Dashboard/DashboardContext.cs
- src/Hangfire.Core/Dashboard/DashboardRoutes.cs
- src/Hangfire.Core/Dashboard/RouteCollectionExtensions.cs
On .NET Core the typical initialization of Hangfire is supposed to look like this:
```c#
services.AddHangfire(options => 
{
options.UseSqlServerStorage("connection string");
// other things, like options.UseConsole();
});
```
and it seems to work (most of the time).
However, in some cases one might want to move storage initialization away from configuration block, and place it directry into IoC container:
```c#
services.AddSingleton<JobStorage>(serviceProvider =>
{
var config = serviceProvider.GetRequiredService<IOptions<DatabaseConfiguration>>().Value;
return new SqlServerStorage(config.ConnectionString, config.Options);
});
services.AddHangfire(options => 
{
// other things
}
```
And there's a very valid reason for that: you can use a standard `IOptions<T>` (or any other) service for …
> Fix issue with configuration block not called on .NET Core + reuse services

- src/Hangfire.Core/Dashboard/JobMethodCallRenderer.cs
Too big job arguments may cause dashboard to fail with the `OutOfMemoryException`, because there are many manipulations with strings here. Despite it's not recommended to have big arguments (it's better to save the data somewhere else and use identifiers instead), we shouldn't cause the whole process to die when one is using them.
Fixes #1051
> Don't render arguments whose size is too big in dashboard

- src/Hangfire.Core/Dashboard/HtmlHelper.cs
This is a simple solution to get `DisplayNameAttribute` working even in .NET Core without including additional references. It's so simple we can include it even to the 1.6.18 release.
> Use reflection to get display name of a job

- src/Hangfire.SqlServer/SqlServerConnection.cs
- tests/Hangfire.SqlServer.Tests/SqlServerConnectionFacts.cs
There are a lot of indexes in the Hash table, and the clustered one is simply based on an incremental id. Without using a lock as in transactions, sooner or later this method will cause a deadlock. Without
using a lock as in transactions, sooner or later this method will cause a deadlock.
In 1.7.0 and later it would be possible to get rid of custom locks, because clustered keys were changed to better organize table's physical structure and remove almost all of the secondary indexes (via #898). But manual sorting would be required. But currently, custom locking is the only option.
Fixes #1124
> Use custom lock in SqlConnection.SetRangeInHash to prevent deadlocks

- src/Hangfire.Core/Server/Worker.cs
- src/Hangfire.Core/States/BackgroundJobStateChanger.cs
- tests/Hangfire.Core.Tests/Server/WorkerFacts.cs
- tests/Hangfire.Core.Tests/States/BackgroundJobStateChangerFacts.cs
There was a change 8570ef77cc349c30ea7d105197aeb0f5d406d7c6 in Hangfire 1.6.12 that added retries for a state changing process in case of exceptions. This was a good fix for handling errors in buggy state filters, but there are two major problems with the implementation:
1. When all retry attempts exhausted, we were applying the `Failed` state by using a "lightweight" state machine that isn't invoking any job filters, resulting in a rare, but possible non-consistent behavior, especially when there's a storage outage (that's recovered just after the last retry attempt), for all the filters that are based on the "previous" state.
2. An exception may be caused by a broken connection. In this case, distributed lock acquired in the `ChangeState` method may be released, if lock implementation …
> Move state change retries to the Worker class

- src/Hangfire.Core/Storage/StorageConnectionExtensions.cs
- tests/Hangfire.Core.Tests/Storage/StorageConnectionExtensionsFacts.cs
Changing the `GetRecurringJobs` to use the `DeserializeNullableDateTime` method when deserializing nullable dates `NextExecution`, `LastExecution`, and `CreatedAt`.
These properties are nullable `DateTime` types and the `DeserializeDateTime` method was throwing errors when a null value was being provided.  Using the null safe method that wraps around `DeserializeDateTime`.
Fixes #1199
> Prevent recurring jobs dashboard from throwing null exception.

- nuspecs/Hangfire.AspNetCore.nuspec
- nuspecs/Hangfire.Core.nuspec
- nuspecs/Hangfire.SqlServer.MSMQ.nuspec
- nuspecs/Hangfire.SqlServer.nuspec
- psake-project.ps1
- src/Hangfire.Core/Common/CancellationTokenExtentions.cs
- src/Hangfire.Core/Hangfire.Core.NetStandard.csproj
- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.Core/Server/BackgroundProcessContext.cs
- src/Hangfire.Core/Server/EveryMinuteThrottler.cs
- src/Hangfire.SqlServer/CountersAggregator.cs
- src/Hangfire.SqlServer/ExpirationManager.cs
- src/Hangfire.SqlServer/SqlServerJobQueue.cs
- tests/Hangfire.Core.Tests/Common/CancellationTokenExtentionsFacts.cs
- tests/Hangfire.Core.Tests/Hangfire.Core.Tests.csproj
Last week I received a report regarding the high CPU spikes that appear after several hours of running Hangfire server with the following profiler trace:
As we can see, the application is busy by constantly invoking the `DateTime.Now` and `WaitHandle.WaitOne` members, and the only place in Hangfire where the `Now` property is used is the [`Throttle`](https://github.com/HangfireIO/Hangfire/blob/f8d3c6342c691663fa54b27a3ab8ac4074cbe4b2/src/Hangfire.Core/Server/EveryMinuteThrottler.cs#L24) method. And it contains both calls to `get_Now` and `WaitOne` methods as in the trace above:
```csharp
while (DateTime.Now.Second != 0)
{
token.WaitHandle.WaitOne(TimeSpan.FromSeconds(1));
token.ThrowIfCancellationRequested();
}
````
But how can this loop generate so many calls to the both methods? When …
> Avoid using the CancellationToken.WaitHandle property

- src/Hangfire.Core/ContinuationsSupportAttribute.cs
- src/Hangfire.SqlServer/SqlServerJobQueueMonitoringApi.cs
Results in a bit better handling of clock skews.
> Replace wall clocks with monotonic ones when calculating local timeouts

- src/Hangfire.Core/AutomaticRetryAttribute.cs
- src/Hangfire.Core/BackgroundJobServer.cs
- src/Hangfire.Core/ContinuationsSupportAttribute.cs
- src/Hangfire.Core/LatencyTimeoutAttribute.cs
- src/Hangfire.Core/Server/BackgroundProcessingServer.cs
- src/Hangfire.Core/Server/DelayedJobScheduler.cs
- src/Hangfire.Core/Server/RecurringJobScheduler.cs
- src/Hangfire.Core/Server/ServerWatchdog.cs
- src/Hangfire.Core/Server/Worker.cs
- src/Hangfire.SqlServer/CountersAggregator.cs
- src/Hangfire.SqlServer/ExpirationManager.cs
- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
- src/Hangfire.SqlServer/SqlServerTimeoutJob.cs
And yet another PR for the logging subsystem. This change is making logger initialization more deterministic and predictable, because it's not intuitive when a static field is initialized. Logger is now initialized when we are creating an instance of the corresponding class, and that's the expected behavior.
> Change all static logger fields to be instance-based

- src/Hangfire.Core/App_Packages/LibLog.1.4/LibLog.cs
Synchronize access to the current log provider, because it is static and should be thread-safe. Though I don't remember any issues related to this behavior, it's not a good idea to have a non-deterministic behavior there that potentially may lead to subtle race conditions.
> Fix `_currentLogProvider` field access to use volatile reads/writes

- src/Hangfire.Core/App_Packages/LibLog.1.4/LibLog.cs
Any exception there may cause the whole application to go down even if we don't use the logging provider of a specified type. For example, there was a bug in `SerilogLogProvider` that didn't account for signature changes, and just referencing the assembly of a newer version even without using the logging provider was caused an application to be killed due to an exception.
> Avoid resolving types and methods for logging in static ctors

- src/Hangfire.Core/Server/DelayedJobScheduler.cs
- tests/Hangfire.Core.Tests/Server/DelayedJobSchedulerFacts.cs
This PR brings two improvements to the `DelayedJobScheduler` class that's responsible for scheduling delayed jobs. Previously it fetched background job identifiers one by one from the schedule, acquiring a distributed lock on each fetch to prevent other scheduler instances from doing the same work. 
Now, it pulls a dozen identifiers at once using the new `GetFirstByLowestScoreFromSet` overload implemented in PR #1251 when it's supported by a storage. If that method isn't available, the new implementation will use the old method, but with increased lifetime of a distributed lock.
Closes #38.
> Optimize implementation of the DelayedJobScheduler class

- src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardRequest.cs
- src/Hangfire.Core/Dashboard/BatchCommandDispatcher.cs
- src/Hangfire.Core/Dashboard/DashboardRequest.cs
- src/Hangfire.Core/Dashboard/Owin/OwinDashboardRequest.cs
Batch commands sometimes iterate over hundreds of background jobs. In case of an application shutdown, there will be unwanted delay that may prevent the graceful shutdown. It is better to allow request to abort instead.
> Add possibility to detect aborted requests in Dashboard UI

- src/Hangfire.Core/App_Packages/LibLog.1.4/LibLog.cs
> Use serilog SourceContext naming convention

- src/Hangfire.Core/Server/DelayedJobScheduler.cs
- src/Hangfire.Core/Server/RecurringJobScheduler.cs
Before acquiring the lock in SqlServerConnection the resource name is modified by prepending schema name:
https://github.com/HangfireIO/Hangfire/blob/0f3d7a3ebf176c8ab90c1315b160d9d85d7cbf59/src/Hangfire.SqlServer/SqlServerConnection.cs#L63
The modified resource name is included in DistributedLockTimeoutException ctor:
https://github.com/HangfireIO/Hangfire/blob/0f3d7a3ebf176c8ab90c1315b160d9d85d7cbf59/src/Hangfire.SqlServer/SqlServerDistributedLock.cs#L218
Since the resource name doesn't match the initial one, it is missed in the scheduler try/catch:
https://github.com/HangfireIO/Hangfire/blob/0f3d7a3ebf176c8ab90c1315b160d9d85d7cbf59/src/Hangfire.Core/Server/RecurringJobScheduler.cs#L240
This sends it to AutomaticRetryProcess wrapper which causes multiple retries and log entries with …
> Fix for catching DistributedLockTimeoutException based on resource name.

- src/Hangfire.SqlServer/SqlServerStorageOptions.cs
If this value is over int.MaxValue then continual errors will be logged as reported in #1069. This will tell the consumer upfront that they have an issue with their settings. Verified based on the [docs for WaitOne](https://docs.microsoft.com/en-us/dotnet/api/system.threading.waithandle.waitone?view=netframework-4.7.2#System_Threading_WaitHandle_WaitOne_System_TimeSpan_).
```
Error occurred during execution of 'Hangfire.SqlServer.ExpirationManager' process. Execution will be retried (attempt #77) in 00:05:00 seconds.
System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.Parameter name: timeout   
at System.Threading.WaitHandle.WaitOne(TimeSpan timeout, Boolean exitContext)   at System.Threading.WaitHandle.WaitOne(TimeSpan …
```
> Add verification to job expiration check interval

- src/Hangfire.Core/States/EnqueuedState.cs
As the title says...
Relates to #550 and #561
> Add support for dashes `-` in queue names

- nuspecs/Hangfire.AspNetCore.nuspec
- psake-project.ps1
- src/Hangfire.AspNetCore/BackgroundJobServerHostedService.cs
- src/Hangfire.AspNetCore/Hangfire.AspNetCore.csproj
- src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs
Adds net461 as a target framework and creates a new NuGet configuration for it. 
See #1487 for rationale.
> Enable Net461 for Hangfire.AspNetCore

- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
This PR exposes `GetInstallScript()` method on `SqlServerObjectInstaller`, so it's easy to get programmatic access to prepared installation script. It could be used in EF migrations like this:
```cs
public partial class Hangfire : Migration
{
protected override void Up(MigrationBuilder migrationBuilder)
{
migrationBuilder.Sql(SqlServerObjectsInstaller.GetInstallScript("dbo", false));
}
protected override void Down(MigrationBuilder migrationBuilder)
{
// not supported. remove manually
}
}
```
> Add GetInstallScript method

- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
Small improvement upon #1231 to allow HTML tags on the title of the dashboard.
> Add HTML tags on Dashboard title

- src/Hangfire.AspNetCore/Hangfire.AspNetCore.csproj
- src/Hangfire.AspNetCore/HangfireApplicationBuilderExtensions.cs
When using Hangfire from an ASP.NET Core 3.0 application, I encountered a version conflict for the 'Microsoft.Extensions.Logging.Abstractions' package. 
Please consider this PR with the following changes for .Net Core 3 compatibility:
- add netcoreapp3.0 target
- add framework reference to 'Microsoft.AspNetCore.App' 
- use 'IHostApplicationLifetime' instead of deprecated 'IApplicationLifetime'
> add netcoreapp3.0 target for .Net Core 3 compatibility

- src/Hangfire.AspNetCore/BackgroundJobServerHostedService.cs
- src/Hangfire.AspNetCore/Hangfire.AspNetCore.csproj
- src/Hangfire.AspNetCore/HangfireEndpointRouteBuilderExtensions.cs
- src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs
Enables ASP.NET Core users using endpoint routing to map the
Hangfire dashboard. This includes adding netcoreapp3.0 to the
target frameworks for Hangfire.AspNetCore.
Thanks @billbogaiv for the wildcard route mapping advice.
> Add MapHangfireDashboard for ASP.NET Core endpoint routing

- src/Hangfire.Core/Dashboard/Pages/FailedJobsPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/FailedJobsPage.cshtml.cs
We're using hangfire with redis in our production. To resolve the OOM exception we've added a filter to expire failed jobs. The dashboard on "hangfire/jobs/failed" gives NullReferenceException when the jobs get expired and are deleted. I saw that the null checks for job.Value are not added for FailedJobs because hangfire doesn't expect failed jobs to be expired.
> Added null checks for expired failed jobs

- src/Hangfire.Core/Dashboard/Pager.cs
**ISSUE**
If you are customizing pages, and want to re-use the existing Paginator HtmlHelper, there is no way to specify additional query string parameters to be included in the pager URLs. This can be the case when you have custom searches or filters and you want those to persist while paging through the data.
**SOLUTION**
Make `Pager.PageUrl` `virtual`, to allow `override` capability by a subclass that maintain state of additional query string variables. After this change, it would be possible to make a custom pager like so:
```
public class CustomPager : Pager
{
private readonly string query;
public CustomPager(int from, int perPage, long total, string query) 
: base(from, perPage, total)
{
this.query = query;
}
public override string PageUrl(int page)
{
var url = base.PageUrl(page); …
```
> Allow Pager.PageUrl to be overridden by a subclass

- src/Hangfire.Core/Dashboard/Content/resx/Strings.fr.resx
I'm not a big fan of translated tools — english is better — but that might help some people!
I could use a review from a fellow french developper for a few words I chose, even though I think it's good to go right now:
Translations I thought of:
- *(Nouvelles) Tentatives / Retenter*
- Relances / Relancer
- Rééssais / Rééssayer
Impact: `RetriesPage_NoJobs`, `RetriesPage_Title`, `RetriesPage_Warning_Html`, `NavigationMenu_Retries`, `Common_Retry`, `JobDetailsPage_JobAbortedNotActive_Warning_Html`
Translations I thought of:
- Unité de travail (choisi)
- Processeur
- Travailleur
- Worker (tel quel)
Impact: `ServersPage_Table_Workers`
Translations I thought of:
- Tâche
- Travail
- Job (tel quel)
Impact: omniprésent
Translations I thought of:
- Pulsation
Impact: `ServersPage_Note_Text`, …
> [Dashboard] French translation

- nuspecs/Hangfire.AspNetCore.nuspec
- nuspecs/Hangfire.Core.nuspec
- nuspecs/Hangfire.NetCore.nuspec
- nuspecs/Hangfire.SqlServer.MSMQ.nuspec
- nuspecs/Hangfire.SqlServer.nuspec
- nuspecs/Hangfire.nuspec
https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository
Adding the repository link allows direct linking from the NuGet gallery to the source repository.
It is also how tools like [renovate-bot](https://github.com/renovatebot/renovate) are able to group "monorepo" packages for updates which must be performed in tandem.
> add repository link to nuspec files

- src/Hangfire.AspNetCore/HangfireServiceCollectionExtensions.cs
This allows the configuration of `BackgroundJobServerOptions` to be based on other services, options, etc..
While there exists the workaround of registering the `BackgroundJobServerOptions` manually
```
services.AddSingleton(provider => {
var other = provider.getRequiredService<OtherOptions>();
return new BackgroundJobServerOptions
{
Queues = new[] { "default", "misc", other.SomeQueueName},
WorkerCount = 1,
};
});
services.AddHangfireServer();
```
This fails if one wants to register multiple HangfireServer with differing configurations (all based on some other service/options).
> Add an overload for AddHangfireServer utilizing IServiceProvider

- src/Hangfire.Core/Obsolete/Job.Obsolete.cs
- src/Hangfire.Core/Server/BackgroundJobPerformer.cs
- src/Hangfire.Core/Server/CoreBackgroundJobPerformer.cs
- src/Hangfire.Core/Server/JobPerformanceException.cs
- tests/Hangfire.Core.Tests/Server/CoreBackgroundJobPerformerFacts.cs
This PR adds a `string JobId` property to the `JobPerformanceException` class so that error logging code (exception handlers, etc) can access the `JobId` that was running that caused this issue.
Initially I was going to provide a `BackgroundJob Job` property instead of a `string JobId` property, but that would not let the exception class be `Serializable` any more.
There is also a few `Obsolete` call code paths I do not pass in the `JobId` so this property could be `null`.
> Added JobId property to JobPerformanceException for error logging purposes

- src/Hangfire.Core/Dashboard/Content/css/hangfire.css
- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml.cs
- src/Hangfire.Core/Dashboard/Pages/_ErrorAlert.cshtml
- src/Hangfire.Core/Dashboard/Pages/_ErrorAlert.cshtml.cs
Before: alerts are not visible after scrolling, sidebar has excess margin
After: alerts are fixed to top and always visible. Sidebar has proper margin
>   Implemented fixed-top behaviour for error alerts

- src/Hangfire.Core/AppBuilderExtensions.cs
Since ConcurrentBag does not support removal of a specific object, and there is no thread-safe set class, here ConcurrentDictionary is used as a Set. Fixes #1877
> Avoid memory leak in AppBuilderExtensions

- src/Hangfire.AspNetCore/HangfireEndpointRouteBuilderExtensions.cs
The current DashboardOptions constructor sets the `LocalRequestsOnlyAuthorizationFilter` as a default filter. When you setup your Hangfire Dashboard using the new endpoints pattern and set an authorization policy it still goes ahead and uses the default anyway. To circumvent it we need to pass an empty list to `Authorization` as shown below.
```
app.UseEndpoints(endpoints =>
{
endpoints.MapControllers()
.RequireAuthorization();
endpoints.MapHangfireDashboard("/dashboard/hangfire", new DashboardOptions()
{
// We need to pass an empty list or Hangfire will use a local authorization filter
Authorization = new List<IDashboardAuthorizationFilter>()
})
.RequireAuthorization("hangfire-specific-auth-scheme");
});
```
The new extension method introduced in this PR supports passing an authorization …
> [Dashboard] AspNetCore 3.0+ authorization policy support via extensions

- src/Hangfire.Core/Dashboard/Content/css/hangfire.css
Implemented fixed-top behaviour for error alerts 
**Before**
**After**
> Remove excess paddings of alert

- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml.cs
Make back-to-site button from image below collapse, for saving space on narrow screens like at the last image of the PR
**Default**
**Collapsed at 768-992px**
> Implemented back-to-site link responsiveness

- src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardMiddleware.cs
- src/Hangfire.Core/Dashboard/IDashboardAsyncAuthorizationFilter.cs
- src/Hangfire.Core/DashboardOptions.cs
Safe and backwards compatible support for async dashboard authorization in when using AspNetCore dashboard middleware.
Only negative thing is that the `AsyncAuthorization` prop can even when not using AspNetCore
I'm not sure if this is intentionally not supported?
> Support async DashboardAuthorization in AspNetCore for Hangfire 1.x

- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
Footer shifts down, when fixed-alert is shown
With this PR it is fixed:
> Fixed footer shift when fixed-alert is shown

- src/Hangfire.Core/Dashboard/Content/css/hangfire.css
Before:
Fixed width, even when screen width is wider than 1200px
After:
For screens of all sizes container width is now relative.
**Wider than 1200px**
**992px - 1200px**
**768 - 992px**
**Narrower than 768px**
> Implemented full-width support

- src/Hangfire.Core/BackgroundJobServerOptions.cs
Fixed incorrect argument validation in `HeartbeatInterval` setter, which was checking against the wrong constant.
Actual behaviour is unchanged since their values are identical.
> Fix incorrect validation for HeartbeatInterval

- src/Hangfire.Core/Dashboard/Content/resx/Strings.de.resx
Only very minor fix: Plural of "Auftrag" in German is "Aufträge" (not "Auftrage").
> Fix 2 typos in German translation

- src/Hangfire.SqlServer/Hangfire.SqlServer.csproj
- src/Hangfire.SqlServer/SqlCommandBatch.cs
- src/Hangfire.SqlServer/SqlCommandSet.cs
- src/Hangfire.SqlServer/SqlServerStorage.cs
- src/Hangfire.SqlServer/SqlServerStorageOptions.cs
- tests/Hangfire.SqlServer.Tests/SqlServerStorageFacts.cs
Use reflection to use either System.Data.SqlClient or Microsoft.Data.SqlClient in order to avoid taking a hard dependency on either one.
It also replaces the `PreferMicrosoftDataSqlClient` boolean property introduced in 751833bb80203710cf20c8d414733fa31d9e88e4 with a `DbProviderFactory` property that is automatically detected with reflection with a preference for System.Data.SqlClient over Microsoft.Data.SqlClient.
Fixes #1735
> Remove dependency on System.Data.SqlClient for Hangfire.SqlServer

- src/Hangfire.SqlServer/SqlServerStorage.cs
It should have been part of cff3c5b39d47aed9323976da5ef30a9196770d9e but was missed.
> Delete the now unused _microsoftDataSqlClientType field

- src/Hangfire.Core/IJobCancellationToken.cs
- src/Hangfire.Core/JobCancellationToken.cs
Updates the `JobCancellationToken` to include intellisense hints for the exception it throws for `ThrowIfCancellationRequested()`.
These comments were taken from CancellationToken comments.
> Document the exception for the Job Cancellation Token

- nuspecs/Hangfire.SqlServer.nuspec
- src/Hangfire.SqlServer/SqlServerStorageOptions.cs
Commit cff3c5b39d47aed9323976da5ef30a9196770d9e made it possible for the consumer to choose between System.Data.SqlClient or Microsoft.Data.SqlClient in order to avoid taking a hard dependency on either one.
So the System.Data.SqlClient dependency must also be removed from the nuspec else it will be used anyway.
> Remove System.Data.SqlClient from the NuGet dependency graph

- src/Hangfire.NetCore/DefaultClientManagerFactory.cs
- src/Hangfire.NetCore/HangfireServiceCollectionExtensions.cs
- src/Hangfire.NetCore/IBackgroundJobClientFactory.cs
- src/Hangfire.NetCore/IRecurringJobManagerFactory.cs
In order to make `IBackgroundJobClientV2` and `IRecurringJobManagerV2` injectable.
> Add IBackgroundJobClientFactoryV2 and IRecurringJobManagerFactoryV2

- src/Hangfire.Core/BackgroundJob.cs
- src/Hangfire.Core/BackgroundJobClientExtensions.cs
- tests/Hangfire.Core.Tests/BackgroundJobClientExtensionsFacts.cs
- tests/Hangfire.Core.Tests/BackgroundJobFacts.cs
We need the ability to reschedule jobs (similar to the requeue functionality) so we decided to contribute the code. I hope that's ok. Hopefully I added all the necessary tests, if not please let me know :).
> Add reschedule functionality to BackgroundJob

- src/Hangfire.Core/Dashboard/Content/css/hangfire-dark.css
Fix when state-card is active. It retained the light background color. The other card states appear to override to transparent.
Before:
After:
> state-card-state-active not very dark

- src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardMiddleware.cs
- src/Hangfire.AspNetCore/Dashboard/AspNetCoreDashboardResponse.cs
ASP.NET Core does not buffer the http response body. This means that the very first time the response is written, the headers are sent along with that chunk of the body to the client. When this happens, it's no longer possible to change response headers.
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md#avoid-adding-headers-after-the-httpresponse-has-started
> Check if response `HasStarted` before changing it.

- src/Hangfire.Core/Dashboard/UrlHelper.cs
The piece of code in question:
```C#
public string To(string relativePath)
{
return _context.Options.PrefixPath +
(
#if FEATURE_OWIN
_owinContext?.Request.PathBase.Value ??
#endif
_context.Request.PathBase
+ relativePath
);
}
```
With FEATURE_OWIN this compiles to the following:
```C#
return _context.Options.PrefixPath +
(_owinContext?.Request.PathBase.Value ??
(_context.Request.PathBase + relativePath));
```
Note how in the Owin case the `relativePath` value is lost.
Not a big deal since the Owin case is deprecated via constructor attribute.
> Fix UrlHelper.To in Obsolete case
