- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
Please see http://discuss.hangfire.io/t/hangfire-deadlocks-on-server-restart/838
> Retry on deadlocks during automatic migration

- src/Hangfire.Core/Dashboard/Content/css/hangfire.css
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.generated.cs
Minor improvements to navigation
* make nav-bar fixed on top of page
* make job side menu fixed for col-md media
These changes also allow the dashboard to be embedded in an iframe in the parent website. The user experience is much better.
> Minor improvements to navigation

- samples/ConsoleSample/Program.cs
- samples/ConsoleSample/Services.cs
- src/Hangfire.Core/BackgroundJob.cs
- src/Hangfire.Core/BackgroundJobClientExtensions.cs
Added generic overloads for BackgroundJob.ContinueWith
Updated samples to use generic version of BackgroundJob.ContinueWith
See issue #350
> Added support for generic continuations

- appveyor.yml
- nuspecs/Hangfire.Core.nuspec
- nuspecs/Hangfire.nuspec
- samples/ConsoleSample/Program.cs
- samples/ConsoleSample/Services.cs
- samples/MvcSample/MvcSample.csproj
- src/Hangfire.Core/BackgroundJob.cs
- src/Hangfire.Core/BackgroundJobClientExtensions.cs
- src/Hangfire.Core/Dashboard/DashboardRoutes.cs
- src/Hangfire.Core/Dashboard/Pages/RetriesPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/RetriesPage.generated.cs
- src/Hangfire.SqlServer.Msmq/MsmqExtensions.cs
- src/SharedAssemblyInfo.cs
* **Added** – Missing generic methods for continuations&nbsp;(#357 by @yngndrw).
* **Fixed** – MSMQ extension does not work without explicit queue names in `UseMsmqQueues`&nbsp;(#360).
* **Fixed** – Missing null-check in Retries page after casting connection to `JobStorageConnection`&nbsp;(#345).
* **Fixed** – Enqueued jobs cannot be deleted from the Dashboard&nbsp;(#342).
* **Fixed** – Error when building the project using `build.bat` on a machine with VS 2013 only&nbsp;(#339 by @Cussa).
> Release 1.4.2

- src/Hangfire.SqlServer/Install.sql
- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
Increased Queue name and Server Id lengths as discussed at #369
> Increase SQL JobQueue.Queue column size

- samples/ConsoleSample/ConsoleSample.csproj
- samples/ConsoleSample/packages.config
- samples/MvcSample/MvcSample.csproj
- samples/MvcSample/packages.config
- src/Hangfire.Core/BackgroundJobClient.cs
- src/Hangfire.Core/Hangfire.Core.csproj
- src/Hangfire.Core/packages.config
- src/Hangfire.SqlServer.Msmq/Hangfire.SqlServer.Msmq.csproj
- src/Hangfire.SqlServer.Msmq/packages.config
- src/Hangfire.SqlServer.RabbitMq/Hangfire.SqlServer.RabbitMq.csproj
- src/Hangfire.SqlServer.RabbitMq/packages.config
- src/Hangfire.SqlServer/CountersAggregator.cs
- src/Hangfire.SqlServer/Hangfire.SqlServer.csproj
- src/Hangfire.SqlServer/SqlServerConnection.cs
- src/Hangfire.SqlServer/packages.config
- tests/Hangfire.Core.Tests/Hangfire.Core.Tests.csproj
- tests/Hangfire.Core.Tests/packages.config
- tests/Hangfire.SqlServer.Msmq.Tests/Hangfire.SqlServer.Msmq.Tests.csproj
- tests/Hangfire.SqlServer.RabbitMq.Tests/Hangfire.SqlServer.RabbitMq.Tests.csproj
- tests/Hangfire.SqlServer.RabbitMq.Tests/packages.config
- tests/Hangfire.SqlServer.Tests/Hangfire.SqlServer.Tests.csproj
- tests/Hangfire.SqlServer.Tests/SqlServerConnectionFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerWriteOnlyTransactionFacts.cs
- tests/Hangfire.SqlServer.Tests/packages.config
Fixes for issue #371 - will work on all databases however changes are significant for users with a BIN collation SQL server.
> Case sensitive changes for BIN collation SQL databases

- src/Hangfire.Core/BackgroundJobServer.cs
- src/Hangfire.Core/RecurringJob.cs
- src/Hangfire.Core/RecurringJobManager.cs
- src/Hangfire.Core/Server/RecurringJobScheduler.cs
For a bonus queue can be specified runtime.
> Run recurrings jobs on per machine basis #379

- README.md
I noticed this when checking out the project details.
> Changed 'were never been' to 'have never been'

- README.md
Lightweight proofreading of the README: fixing commas, some articles, a
tense or two, etc.
> README Grammar Corrections

- src/Hangfire.SqlServer/SqlServerJobQueue.cs
- src/Hangfire.SqlServer/SqlServerJobQueueMonitoringApi.cs
- src/Hangfire.SqlServer/SqlServerMonitoringApi.cs
- src/Hangfire.SqlServer/SqlServerObjectsInstaller.cs
- src/Hangfire.SqlServer/SqlServerStorage.cs
- src/Hangfire.SqlServer/SqlServerWriteOnlyTransaction.cs
Same as https://github.com/HangfireIO/Hangfire/pull/524, just targetting dev branch
> Refactored SqlServerStorage to use the more general DbConnection - Take2

- src/Hangfire.SqlServer.Msmq/MessageQueueExtensions.cs
This fixes the dashboard crashing when using MSMQ, as discussed in: https://discuss.hangfire.io/t/dashboard-appears-broken-in-hangfire-1-5-2/1438/12
> Fix dashboard crashing when using MSMQ

- src/Hangfire.AspNetCore/AspNetCore/AspNetCoreJobActivator.cs
> Fix BeginScope() returning SimpleJobActivatorScope

- src/Hangfire.Core/Dashboard/Pages/JobDetailsPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/JobDetailsPage1.generated.cs
`JobDetailsPage1.generated.cs` was modified in PR #674 but related `JobDetailsPage.cshtml` was not modified.
This PR adds missing changes.
> Add missing changes to JobDetailsPage.cshtml from JodDetailsPage1.generated.cs

- src/Hangfire.Core/Dashboard/Content/js/hangfire.js
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/LayoutPage.generated.cs
Fix for issue https://github.com/HangfireIO/Hangfire/issues/696
> Replace inline script, because it may violate the Content Security Policy

- .nuget/packages.config
- .travis.yml
- tests/Hangfire.Core.Tests/BackgroundJobFacts.cs
We can again test Hangfire inside Mono environment after [nuget issue 3085](https://github.com/NuGet/Home/issues/3085) issue was closed.
> Run tests inside Mono environment again.

- README.md
This PR fixes broken links to documentation in Readme.md file.
> Fix broken links in Readme file.

- src/Hangfire.SqlServer/SqlServerDistributedLock.cs
> Don't leak connection, when distributed lock can't be acquired

- src/Hangfire.Core/Storage/InvocationData.cs
- tests/Hangfire.Core.Tests/Storage/InvocationDataFacts.cs
> Adjusting deserialization of datetime to use RoundTripKind

- src/Hangfire.Core/GlobalConfigurationExtensions.cs
- src/Hangfire.Core/JobStorage.cs
- src/Hangfire.Core/States/ApplyStateContext.cs
- tests/Hangfire.Core.Tests/JobStorageFacts.cs
- tests/Hangfire.Core.Tests/States/ApplyStateContextFacts.cs
Hello,
The idea is make it possible to configure expiration timeout for jobs :)
Best regards.
> JobStorage has a prop to define job expiration timeout

- src/Hangfire.SqlServer/SqlServerMonitoringApi.cs
Don't crash when trying to access keys which don't exist (Issue #871)
Replaced the use of dictionary[key] with a minimally overridden version that returns default(TValue) instead of throwing - this fixes assorted failures in the query api when there are lots of old historical jobs with invalid function signatures, deleted data, etc.
> more complete fix for issue #871 - 

- src/Hangfire.Core/Dashboard/Pages/ServersPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/ServersPage.generated.cs
> Fix server start time tooltip position

- README.md
Mention that Razor Generator is required to modify the Razor views.
> Update README.md to mention Razor Generator

- src/Hangfire.Core/Dashboard/DashboardMetrics.cs
- src/Hangfire.Core/Dashboard/Metric.cs
- src/Hangfire.SqlServer/SqlServerStorage.cs
> Provide IntValue for all metrics

- src/Hangfire.SqlServer/SqlServerStorage.cs
- src/Hangfire.SqlServer/SqlServerStorageExtensions.cs
- tests/Hangfire.SqlServer.Tests/SqlServerStorageFacts.cs
> Add connection factory overload for SqlServerStorage

- src/Hangfire.SqlServer/SqlServerWriteOnlyTransaction.cs
- tests/Hangfire.SqlServer.Tests/SqlServerWriteOnlyTransactionFacts.cs
`SqlServerStorageOptions.CommandBatchMaxTimeout` option allows issue all the commands in a transaction with a single round-trip to database by using the internal `SqlCommandSet` class from ADO.NET. This feature greatly reduces the lifetime of a transaction, increasing the overall throughput.
Currently job queue provider's queries were unable participate in a command batch, but this PR changes that, so `AddToQueue` method will be placed into a batch rather than be running as separate queries.
> Batch support for AddToQueue method when default queue provider is used

- src/Hangfire.Core/Cron.cs
- tests/Hangfire.Core.Tests/CronFacts.cs
convenience method for never-firing recurring jobs
> Added Cron.Never()

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-BR.resx
The translation process was based on Strings.es.resx file
> dashboard localization support in pt-BR

- tests/Hangfire.SqlServer.Tests/CountersAggregatorFacts.cs
- tests/Hangfire.SqlServer.Tests/ExpirationManagerFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerConnectionFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerJobQueueFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerTimeoutJobFacts.cs
- tests/Hangfire.SqlServer.Tests/SqlServerWriteOnlyTransactionFacts.cs
I made these changes while working through #1531 if you want to include them.
> Use schema from constant in tests

- README.md
> minor changes in readme.md 

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-PT.resx
- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt.resx
Hi everyone,
this is my first pull request hope you find it interesting.
Added translations for pt and pt-PT
Keep on the good work
best wishes
> Portuguese translation added

- src/Hangfire.Core/Dashboard/UrlHelper.cs
- src/Hangfire.Core/DashboardOptions.cs
- tests/Hangfire.Core.Tests/Dashboard/DashboardOptionsFacts.cs
> Add PrefixPath in DashboardOptions.

- src/Hangfire.Core/Server/AspNetShutdownDetector.cs
Fixes https://github.com/HangfireIO/Hangfire/issues/1784
> Fix race condition in AspNetShutdownDetector and warnings

- src/Hangfire.Core/Dashboard/Content/resx/Strings.nb.resx
Hopefully this will fall back successfully for people using `nb-NO` as well 😅🤞🏻
> [Dashboard] Added Norwegian translations

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-BR.resx
Just a couple of spelling mistakes I noticed.
> Correction on brazilian portuguese translations

- src/Hangfire.Core/Dashboard/Content/css/hangfire.css
- src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml
- src/Hangfire.Core/Dashboard/Pages/RecurringJobsPage.cshtml.cs
This PR fixes problem described in this issue: https://github.com/HangfireIO/Hangfire/issues/1859
> Fixed badge behaviour for too long CRON expressions

- nuspecs/Hangfire.Core.nuspec
- nuspecs/Hangfire.nuspec
Update my GitHub user handle in the release notes
> Update GitHub user handle in Hangfire.Core release notes (rename)

- src/Hangfire.Core/Dashboard/Content/resx/Strings.tr-TR.resx
I added to turkish language support for dashboard.
> Dashboard Turkish langauge support

- src/Hangfire.Core/Dashboard/Content/resx/Strings.tr-TR.resx
Some of the translations were hard to understand.
> Fixing translations in Turkish translation

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-BR.resx
Changing pt-BR translation file to resolve this issue: https://github.com/HangfireIO/Hangfire/issues/2071
> update pt-BR translation file

- src/Hangfire.Core/Dashboard/Content/resx/Strings.sv.resx
Adds a first version of Swedish translation of the dashboard.
> Swedish translation

- CONTRIBUTING.md
Correct grammar fix, "stick" in 3rd form is stuck, not stucked.
https://ell.stackexchange.com/questions/85624/stucked-is-it-correct
> Fix: grammar error

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-BR.resx
- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-PT.resx
- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt.resx
- fix typos
- added missing
- improve grammar
Hi @odinserj 
I've read the contributing readme, I didn't see anything about making a PR, if there is something else needed, please let me know.
There's some major typos I'd like to have fixed on the dashboard.
> Improve portuguese translations

- src/Hangfire.Core/Dashboard/Content/resx/Strings.nb.resx
Added translations for new entries since the initial translation 😄
> Added Norwegian translations for new keys

- src/Hangfire.Core/Dashboard/Content/resx/Strings.sv.resx
Found 2 very minor errors in the Swedish localization file.
I have not created an issue for this since it's such a small thing, but I can absolutely create one if it's needed! :)
> 2 minor localization errors in Strings.sv.resx

- src/Hangfire.Core/Processing/BackgroundExecution.cs
> Reformulate misleading error messages

- src/Hangfire.Core/Dashboard/Content/resx/Strings.pt-BR.resx
This pull request fixes several Portuguese language issues and improves consistency in the XML resource file.
Corrections made:
- Fixed typo: corrected "aparentamente" to "aparentemente".
- Fixed typo: corrected "Painel de Controlo" to "Painel de Controle".
- Fixed gender agreement: changed "foi processado" to "foi processada".
- Corrected pronoun: changed "Ele será recuperado" to "Ela será recuperada".
etc.
> [FEAT] - Fix Portuguese (Brazil) translations in Strings.pt-BR.resx
